openapi: 3.0.0
info:
  title: チャンネル局マスタ検索
  description: チャンネル局IDによって区分マスタを返す
  version: 1.0.0
servers:
  - url: https://localhost:8082
    description: チャンネル局マスタ検索
paths:
  /channelKyoku/{channelIds}}:
    get:
      tags:
        - channelKyoku
      operationId: getChannelKyoku
      summary: チャンネル局マスタをチャンネル局IDによって取得する
      description: チャンネル局マスタをチャンネル局IDによって取得する
      parameters:
        - in: path
          name: channelIds
          required: true
          schema:
            type: string
            maxLength: 100
      responses:
        '200':
          description: チャンネル局マスタを正常取得
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/channelKyoku'      
components:
  schemas:
    channelKyoku:
      description: チャンネル局マスタ
      type: object
      properties:
        mChannelKyoku:
          description: チャンネル局マスタDTO
          type: array
          items:
            $ref: "../../TalentSearchCommon/Tables/mChannelKyoku.yaml#/components/schemas/mChannelKyoku"