openapi: 3.0.0
info:
  title: 年月週管理参照検索
  description: 年月、週によって年月週管理情報を返す
  version: 1.0.0
servers:
  - url: https://localhost:8082
    description: 年月週管理参照検索
paths:
  /nentsukiShuKanrRef:
    get:
      tags:
        - nentsukiShuKanrRef
      operationId: getNentsukiShuKanrRef
      summary: 年月、週によって年月週管理情報を返す
      description: 年月、週によって年月週管理情報を返す
      parameters:
        - in: query
          name: nentsuki
          required: true
          description: 年月
          schema:
            type: integer
            maximum: 210012
            minimum: 199001
        - in: query
          name: shu
          required: true
          description: 週
          schema:
            type: integer
            maximum: 5
            minimum: 1
      responses:
        '200':
          description: 年月週管理情報を正常取得
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/mNentsukiShuKanri'
components:
  schemas:
    mNentsukiShuKanri:
      description: 年月週管理マスタDTO
      type: object
      properties:
        items:
          $ref: "../../TalentSearchCommon/Tables/mNentsukiShuKanri.yaml#/components/schemas/mNentsukiShuKanri"