openapi: 3.0.0
info:
  title: 年月週管理登録・更新
  description: 年月週管理マスタ情報を登録または更新する
  version: 1.0.0
servers:
  - url: https://localhost:8082
    description: 年月週管理マスタ情報を登録または更新する
paths:
  /nentsukiShuKanri:
    get:
      tags:
        - nentsukiShuKanri
      operationId: getNentsukiShuKanri
      summary: 年月週管理マスタを返す
      description: 年月週管理マスタ情報を返す
      responses:
        '200':
          description: 年月週管理マスタDTOの情報
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/getNentsukiShuKanri'
    post:
      tags:
        - nentsukiShuKanri
      operationId: postProgramTorokuKoshin
      summary: 年月週管理マスタ情報を登録または更新する
      description: 年月週管理マスタ情報を登録または更新する
      requestBody:
        description: 年月週管理マスタ情報を登録または更新する
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/postNentsukiShuKanri'
      responses:
        '200':
          description: 登録または更新した年月週管理マスタDTOの情報
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/postNentsukiShuKanri'
components:
  schemas:
    postNentsukiShuKanri:
      description: 登録または更新した年月週管理マスタDTOの情報
      type: object
      properties:
          items:
            $ref: "../../TalentSearchCommon/Tables/mNentsukiShuKanri.yaml#/components/schemas/mNentsukiShuKanri"
    getNentsukiShuKanri:
      description: 年月週管理マスタDTOの情報
      type: object
      properties:
        mNentsukiShuKanri:
          description: 年月週管理マスタDTOの情報
          type: array
          items:
            $ref: "../../TalentSearchCommon/Tables/mNentsukiShuKanri.yaml#/components/schemas/mNentsukiShuKanri"
