openapi: 3.0.0
info:
  title: オンエア管理テーブル検索
  description: オンエア管理テーブルの情報を返す
  version: 1.0.0
servers:
  - url: https://localhost:8082
    description: オンエア管理テーブル検索
paths:
  /onAirKanri/{id}:
    get:
      tags:
        - onAirKanri
      operationId: getOnAirKanri
      summary: オンエア管理テーブル情報を返す
      description: オンエア管理テーブル情報を返す
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            maxLength: 8
      responses:
        '200':
          description: オンエア管理テーブルDTOの情報を正常取得
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/onAirKanriList'
  /onAirKanri:
    post:
      tags:
        - onAirKanri
      operationId: postOnAirKanri
      summary: オンエア管理テーブル情報を登録または更新する
      description: オンエア管理テーブル情報を登録または更新する
      requestBody:
        description: オンエア管理テーブル情報を登録または更新する
        content:
          application/json:
            schema:
              $ref: "../../TalentSearchCommon/Tables/tOnAirKanri.yaml#/components/schemas/tOnAirKanri"
      responses:
        '200':
          description: 登録または更新したオンエア管理テーブルDTOの情報
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/onAirKanriList'
components:
  schemas:
    onAirKanriList:
      description: オンエア管理テーブルDTOの情報
      type: object
      properties:
        tOnAirKanri:
          description: オンエア管理テーブルDTO
          type: array
          items:
            $ref: "../../TalentSearchCommon/Tables/tOnAirKanri.yaml#/components/schemas/tOnAirKanri"
 