openapi: 3.0.0
info:
  title: オンエア管理参照検索
  description: ID、オンエア日によってオンエア管理情報を返す
  version: 1.0.0
servers:
  - url: https://localhost:8082
    description: オンエア管理参照検索
paths:
  /onAirKanriRef:
    get:
      tags:
        - onAirKanriRef
      operationId: getOnAirKanriRef
      summary: ID、オンエア日によってオンエア管理情報を返す
      description: ID、オンエア日によってオンエア管理情報を返す
      parameters:
        - in: query
          name: id
          required: false
          description: ID
          schema:
            type: string
            maxLength: 8
        - in: query
          name: onAirDay
          required: false
          description: オンエア日
          schema:
            type: string
            format: yyyy/MM/dd
      responses:
        '200':
          description: オンエア管理情報を正常取得
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/tOnAirKanriInfo'
components:
  schemas:
    tOnAirKanriInfo:
      description: オンエア管理テーブル情報
      type: object
      properties:
        items:
          $ref: "../../TalentSearchCommon/Tables/tOnAirKanri.yaml#/components/schemas/tOnAirKanri"