openapi: 3.0.0
info:
  title: 番組参照検索
  description: 番組ID、番組名によって番組情報を返す
  version: 1.0.0
servers:
  - url: https://localhost:8082
    description: 番組参照検索
paths:
  /programRef:
    get:
      tags:
        - programRef
      operationId: getProgramRef
      summary: 番組ID、番組名によって番組情報を返す
      description: 番組ID、番組名によって番組情報を返す
      parameters:
        - in: query
          name: programId
          required: false
          description: 番組ID
          schema:
            type: string
            maxLength: 8
        - in: query
          name: programName
          required: false
          description: 番組名
          schema:
            type: string
            maxLength: 30
      responses:
        '200':
          description: 番組情報を正常取得
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/programInfo'
components:
  schemas:
    programInfo:
      description: 番組マスタ情報DTO
      type: object
      properties:
        items:
          $ref: "../../TalentSearchCommon/Tables/mProgram.yaml#/components/schemas/mProgram"