openapi: 3.0.0
info:
  title: 番組マスタ検索
  description: 番組IDによって番組情報を返す
  version: 1.0.0
servers:
  - url: https://localhost:8082
    description: 番組マスタ検索
paths:
  /programInfo/{programId}:
    get:
      tags:
        - programInfo
      operationId: getProgramInfo
      summary: 番組情報を番組IDによって取得する
      description: 番組情報を番組IDによって取得する
      parameters:
        - in: path
          name: programId
          required: true
          schema:
            type: string
            maxLength: 8
      responses:
        '200':
          description: 番組情報を正常取得
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/programInfoList'
components:
  schemas:
    programInfoList:
      description: 番組マスタ情報DTO
      type: object
      properties:
        mProgram:
          description: 番組マスタDTO
          type: array
          items:
            $ref: "../../TalentSearchCommon/Tables/mProgram.yaml#/components/schemas/mProgram"
 