openapi: 3.0.0
info:
  title: 番組登録・更新
  description: 番組情報を登録または更新する
  version: 1.0.0
servers:
  - url: https://localhost:8082
    description: 番組登録・更新
paths:
  /programTorokuKoshin:
    post:
      tags:
        - programTorokuKoshin
      operationId: postProgramTorokuKoshin
      summary: 番組情報を登録または更新する
      description: 番組情報を登録または更新する
      requestBody:
        description: 番組情報を登録または更新する
        content:
          application/json:
            schema:
              $ref: "../../TalentSearchCommon/Tables/mProgram.yaml#/components/schemas/mProgram"
      responses:
        '200':
          description: 登録または更新した番組マスタ情報
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/programTorokuKoshin'      
components:
  schemas:
    programTorokuKoshin:
      description: 登録または更新した番組マスタ情報
      type: object
      properties:
          items:
            $ref: "../../TalentSearchCommon/Tables/mProgram.yaml#/components/schemas/mProgram"