openapi: 3.0.0
info:
  title: 週間タレント別情報
  description: １週間においてのタレントごとの情報をする
  version: 1.0.0
servers:
  - url: https://localhost:8080
    description: 週間タレント別情報
paths:
  /ShukanTalentJoho:
    get:
      tags:
        - ShukanTalentJoho
      operationId: getShukanTalentJoho
      summary: １週間においてのタレントごとの情報を返す
      description: １週間においてのタレントごとの情報を返す
      parameters:
        - in: query
          name: nentsuki
          required: true
          schema:
            type: integer
            maximum : 210012
            minimum : 199001
        - in: query
          name:  shu
          required: true
          schema:
            type: integer
            maximum : 5
            minimum : 1
        - in: query
          name: talentName
          required: false
          schema:
            type: string
            maxLength: 30
      responses:
        '200':
          description: １週間においてのタレントごとの情報を正常取得
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ShukanTalentJoho'
components:
  schemas:
    ShukanTalentJoho:
      description: １週間においてのタレントごとの情報
      type: object
      properties:
        mTalent:
          description: タレントマスタDTO
          type: array
          items:
          $ref: "../../TalentSearchCommon/Tables/mTalent.yaml#/components/schemas/mTalent"
        tOnAirKanri:
          description: オンエア管理テーブルDTO
          type: array
          items:
          $ref: "../../TalentSearchCommon/Tables/tOnAirKanri.yaml#/components/schemas/tOnAirKanri"
        mProgram:
          description: 番組マスタDTO
          type: array
          items:
          $ref: "../../TalentSearchCommon/Tables/mProgram.yaml#/components/schemas/mProgram"
 