openapi: 3.0.0
info:
  title: タレント週間出演情報検索
  description: タレントにおいての１週間ごとの情報をする
  version: 1.0.0
servers:
  - url: https://localhost:8080
    description: タレント週間出演情報検索
paths:
  /TalentShukanShutsuenJoho:
    get:
      tags:
        - TalentShukanShutsuenJoho
      operationId: getTalentShukanShutsuenJoho
      summary: タレントにおいての１週間ごとの情報を返す
      description: タレントにおいての１週間ごとの情報を返す
      parameters:
        - in: query
          name: nentsuki
          required: true
          schema:
            type: integer
            maximum : 210012
            minimum : 199001
        - in: query
          name: shu
          required: true
          schema:
            type: integer
            maximum : 5
            minimum : 1
        - in: query
          name: talentId
          required: true
          schema:
            type: string
            maxLength: 8
      responses:
        '200':
          description: タレントにおいての１週間ごとの情報を正常取得
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/talentShukanShutsuenJoho'
components:
  schemas:
    talentShukanShutsuenJoho:
      description: タレントにおいての１週間ごとの情報
      type: object
      properties:
        tOnAirKanri:
          description: オンエア管理テーブルDTO
          type: array
          items:
           $ref: "../../TalentSearchCommon/Tables/tOnAirKanri.yaml#/components/schemas/tOnAirKanri"
        mTalent:
          description: タレントマスタDTO
          type: array
          items:
           $ref: "../../TalentSearchCommon/Tables/mTalent.yaml#/components/schemas/mTalent"
        mProgram:
          description: 番組マスタDTO
          type: array
          items:
           $ref: "../../TalentSearchCommon/Tables/mProgram.yaml#/components/schemas/mProgram"
        mChanelKyoku:
          description: チャンネル局マスタDTO
          type: array
          items:
           $ref: "../../TalentSearchCommon/Tables/mChanelKyoku.yaml#/components/schemas/mChanelKyoku"
        mKbnGenre:
          description: 区分ジャンルマスタDTO
          type: array
          items:
           $ref: "../../TalentSearchCommon/Tables/mKbnGenre.yaml#/components/schemas/mKbnGenre"
